## Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [3]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# print(dataset.DESCR)

In [7]:
dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
import pandas as pd
import numpy as np

In [10]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
df['target']=dataset.target

In [12]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

As we can see target variable is multiclass having three classes , firstly lets focus on solving binary classification problem

In [13]:
## Binary Classification
df_copy=df[df['target']!=2]

In [14]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

Independent and dependent features

In [15]:
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [16]:
from sklearn.linear_model import LogisticRegression

Train test split

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=20, random_state=42)

In [18]:
logistic_obj=LogisticRegression()
logistic_obj

LogisticRegression()

In [19]:
logistic_obj.fit(x_train,y_train)

LogisticRegression()

In [20]:
# classifier.predict_proba(x_test)

In [21]:
y_pred=logistic_obj.predict(x_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [22]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

we can observe y_predicted and y_test data exactly matching means 100 % accuracy

### Confusion matrix,accuracy score,classification report

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [24]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



As we can see 100 percent accuracy

As the accuracy of the model is 100 percent there is no need of hyperparameter tuning, doing just for learning purpose

### Hyperparameter Tuning

Gridsearchcv

In [25]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [26]:
parameters={'penalty':('l1','l2','elasticnet',None),'C':[1,10,20]}

In logistic regression, the "C" value refers to the regularization parameter used in the regularization process to prevent overfitting of the model. Regularization adds a penalty to the loss function used to train the model, helping to keep the model parameters small and thereby reducing the risk of overfitting. The specific type of regularization used can be either L1 (Lasso) or L2 (Ridge) regularization.

Here's what the "C" value represents:

Inverse of Regularization Strength: The "C" parameter is the inverse of the regularization strength (lambda, 
𝜆
λ). Mathematically, 
𝐶
=
1
𝜆
C= 
λ
1
​
 . A smaller value of 
𝐶
C implies a stronger regularization, while a larger value of 
𝐶
C implies weaker regularization.

Balancing Fit and Complexity: Regularization helps to balance the fit of the model with its complexity. By tuning the "C" value, you can control how much the model should prioritize minimizing the error on the training data versus keeping the model parameters small to generalize better on unseen data.

In [27]:
Grid_obj=GridSearchCV(logistic_obj,param_grid=parameters,cv=5)
Grid_obj

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [28]:
## Splitting of Train data to validation data
Grid_obj.fit(x_train,y_train)   # will give best parameter to use 

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [29]:
Grid_obj.best_params_

{'C': 1, 'penalty': 'l2'}

In [30]:
Logistic_obj_hypertuning=LogisticRegression(C=1,penalty='l2')
Logistic_obj_hypertuning

LogisticRegression(C=1)

In [31]:
Logistic_obj_hypertuning.fit(x_train,y_train)

LogisticRegression(C=1)

In [32]:
y_pred=Logistic_obj_hypertuning.predict(x_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



Reandomized Searchcv

In [33]:
from sklearn.model_selection import RandomizedSearchCV

In [34]:
random_obj_hypertuning=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)
random_obj_hypertuning

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [35]:
random_obj_hypertuning.fit(x_train,y_train) # will fit the best parameter to use for model training

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [36]:
random_obj_hypertuning.best_params_

{'penalty': 'l2', 'C': 10}

Now we need to do same thing as GridSearchCV